### ISSUE TITLE
PyPi link issue

### ISSUE THREAD

**Issue by iwalucas** [shinneider/django-admin-inline-paginator#1]
Great feature, thanks!

One comment, the PyPi (https://pypi.org/project/django-admin-inline-paginator/) project link is pointing to the wrong place: 
`https://github.com/shinneider/django_admin_inline_paginator`
instead of 
`https://github.com/shinneider/django-admin-inline-paginator`

**Comment by pymike00** [comment]
Hi there,

The project is indeed really cool, thanks for sharing it!

I second @iwalucas , I came here through PyPi but the link to your repo is broken.

Best

**Comment by shinneider** [comment]
Hi @pymike00 and @iwalucas 

Sorry for the long time to response, i was moving to another country, and i was problematic steps and I didn't have time.
but now it's all ok.

Thanks for report this, 
is a error on setup file, but it's solved now.

I really apreciate yours colaborations :)
