### ISSUE TITLE
Add `mypy` stub files for `admin.py`

### ISSUE THREAD

**Issue by aitorres** [shinneider/django-admin-inline-paginator#14]
Hi everyone! I am trying to use this package on a project that has `mypy` type checking as part of the CI/CD, and I had to deactivate type-checks on my admin models that use the `TabularInlinePaginated` class since there are no type [stub files](https://mypy.readthedocs.io/en/stable/stubs.html).

I think a `.pyi` stub file for `admin.py` can be constructed upon the [stubs for Django's `admin/options.pyi`](https://github.com/typeddjango/django-stubs/blob/master/django-stubs/contrib/admin/options.pyi).

If it seems like a good idea, I can work on it and submit a PR with the stub!

**Comment by shinneider** [comment]
@aitorres  is a valid point!

You can work at PR, which I'll approve

**Comment by shinneider** [comment]
@aitorres i generated a new version `0.3.0` with your type hint and [ISSUE-18](https://github.com/shinneider/django-admin-inline-paginator/issues/18) (your PR, removing ugetext).

update your requirements please.
