### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by iwalucas** [shinneider/django-admin-inline-paginator#2]
Could you add the license (MIT) that you added on PyPi here as well?

**Comment by shinneider** [comment]
Hi 

Sorry for the long response, i was moving to another country, and i was problematic steps and I didn't have time.
but now it's all ok.

thanks for report this, i added MIT LICENSE on 0.1.1 version. available on pypi now.

**Comment by shinneider** [comment]
Hi @iwalucas 

Sorry for the long response, i was moving to another country, and i was problematic steps and I didn't have time.
but now it's all ok.

thanks for report this, i added MIT LICENSE on 0.1.1 version. available on pypi now.
