### ISSUE TITLE
Bug with delete

### ISSUE THREAD

**Issue by P3RI9** [shinneider/django-admin-inline-paginator#22]
Hi. I think that there is a bug with the library. The "Delete" checkbox column it isn't shown. Am I doing something wrong?

**Comment by andreiavram** [comment]
There's a default set on `TabularInlinePaginated` for `can_delete=False`. You can override that:

```
class YourTabularInline(TabularInlinePaginated):
    model = YourModel
    per_page = 25
    can_delete = True
```

**Comment by P3RI9** [comment]
Thanks! Didn't see in docs
