### ISSUE TITLE
No pagination buttons are shown.

### ISSUE THREAD

**Issue by true-ant** [shinneider/django-admin-inline-paginator#32]
I installed `django-admin-inline-paginator 0.4.0` and I use python 3.10.11,
```
class ModelWithFKAdminInline(ReadOnlyAdminMixin, NestedTabularInline, TabularInlinePaginated):
    fields = (...)
    per_page = 5
    model = ModelWithFK
```
It shows 5 items, but no pagination buttons are shown that only first 5 items are shown.

**Comment by diamonddev107** [comment]
I think you need to customize template file to have pagination.
Or you can have only TabularInlinePaginated.

**Comment by true-ant** [comment]
Thanks @diamonddev107 for your reply. I will check that.

**Comment by true-ant** [comment]
Awesome!!!
I customized `templates\nesting\admin\inlines\tabular.html` with pagination and it works well for me.
