### ISSUE TITLE
delete checkbox missing

### ISSUE THREAD

**Issue by mzduchon** [shinneider/django-admin-inline-paginator#6]
a normal inline has the Delete? checkbox

**Comment by luisjorge129** [comment]
Hi, you can add the `can_delete = True` attribute to your Inline Admin Model, Django for default has this attribute True but for some reason while using this plugin is False by default:

Example:

```
from django_admin_inline_paginator.admin import TabularInlinePaginated

class ModelWithFKAdminInline(TabularInlinePaginated):
    model = ModelWithFK
    fields = (...)
    can_delete = True
```

**Comment by mzduchon** [comment]
Thanks!
